version: "3.8"
services:
  web:
    restart: always
    build: .
    environment:
      - "TZ=Singapore"
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=5000
    volumes:
      - ".:/ict3102-Team17-2021"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.5
